import { ReactNode } from 'react'
import { DM_Sans } from 'next/font/google'

const dmSans = DM_Sans({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  fallback: ['Poppins'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={dmSans.className}>{children}</body>
    </html>
  )
}
